name: ai_logo_design
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas=1.3.2
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - opencv=4.5.5
  - pip:
    - requests==2.27.1
    - tqdm==4.62.3
    - opencv-contrib-python==4.5.5.64